// Reads the snarkjs BLS12-381 verification key and emits a Rust source file
// (src/vk.rs) with the verifying-key points encoded as Soroban byte arrays.
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { g1ToHex, g2ToHex } from "./bls_utils.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function arr(hex) {
  const out = [];
  for (let i = 0; i < hex.length; i += 2) out.push("0x" + hex.slice(i, i + 2));
  return out.join(", ");
}

function main() {
  const vkPath = path.join(__dirname, "..", "bls", "verification_key.json");
  const vk = JSON.parse(fs.readFileSync(vkPath, "utf8"));

  const alpha = g1ToHex(vk.vk_alpha_1);
  const beta = g2ToHex(vk.vk_beta_2);
  const gamma = g2ToHex(vk.vk_gamma_2);
  const delta = g2ToHex(vk.vk_delta_2);
  const ic = vk.IC.map(g1ToHex);

  let out = "// AUTO-GENERATED by circuits/scripts/gen_vk_rs.mjs — do not edit.\n";
  out += "// BLS12-381 Groth16 verifying key, Soroban uncompressed byte encoding.\n\n";
  out += `pub const VK_ALPHA_G1: [u8; 96] = [${arr(alpha)}];\n\n`;
  out += `pub const VK_BETA_G2: [u8; 192] = [${arr(beta)}];\n\n`;
  out += `pub const VK_GAMMA_G2: [u8; 192] = [${arr(gamma)}];\n\n`;
  out += `pub const VK_DELTA_G2: [u8; 192] = [${arr(delta)}];\n\n`;
  out += `pub const VK_IC_LEN: usize = ${ic.length};\n\n`;
  out += `pub const VK_IC: [[u8; 96]; ${ic.length}] = [\n`;
  for (const p of ic) out += `    [${arr(p)}],\n`;
  out += "];\n";

  const dest = path.join(
    __dirname,
    "..",
    "..",
    "contracts",
    "voting_contract",
    "src",
    "vk.rs"
  );
  fs.writeFileSync(dest, out);
  console.log("Wrote", dest);
  console.log("nPublic:", vk.nPublic, "IC length:", ic.length);
}

main();
